alias cls="clear"
alias shnow="sudo shutdown now"
alias pdf="zathura"
alias p="sudo pacman"
alias ls="exa --icons"
alias l="exa --icons -la"
alias ll="exa --icons -lh"
alias lsa="exa --icons -lah"
alias ra="ranger"
alias vim="nvim"
alias gt="git log --graph --decorate --pretty=oneline --abbrev-commit"
alias gs="git status"
alias gc="git commit"
alias ga="git add"
alias gaa="git add --all"
alias gd="git diff"
alias gp="git push"
