alias cls="clear"
alias shnow="sudo shutdown now"
alias pdf="zathura"
alias p="sudo pacman"
alias ls="exa --icons"
alias ra="ranger"
alias vim="nvim"
alias tree="log --graph --decorate --pretty=oneline --abbrev-commit"
