[commands.swipe.three]
left_up = ""
right_up = ""
up = "bspc node -t fullscreen"
left_down = ""
right_down = ""
down = "scratch-hide"
left = "bspc desktop -f prev"
right = "bspc desktop -f next"

[commands.swipe.four]
left_up = ""
right_up = ""
up = "scratch-show"
left_down = ""
right_down = ""
down = "bspc node -t tiled"
left = ""
right = ""
