[commands.swipe.three]
left_up = ""
right_up = ""
up = "bspc node -t fullscreen"
left_down = ""
right_down = ""
down = "bspc node -t tiled"
left = "bspc desktop -f prev"
right = "bspc desktop -f next"

[commands.swipe.four]
left_up = ""
right_up = ""
up = "$TERMINAL --working-directory $HOME"
left_down = ""
right_down = ""
down = "bspc node -t floating"
left = ""
right = ""
