#!/bin/sh

"$HOME"/.config/polybar/launch.sh
hsetroot -solid "#FB4934"
picom -b
setxkbmap -option "caps:swapescape"

gap=5
PANEL_HEIGHT=30
bspc config window_gap          $gap;
bspc config top_padding         $PANEL_HEIGHT - $gap
bspc config left_padding        -$gap
bspc config right_padding       -$gap
bspc config bottom_padding      -$gap
bspc config border_width        0

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config single_monocle       true

bspc config focused_border_color  "#282828"
bspc config normal_border_color   "#282828"
bspc config urgent_border_color   "#282828"

bspc config pointer_modifier super
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none
bspc config focus_follows_pointer true

bspc rule -a Blueman-manager state=floating
bspc rule -a Zoom state=floating
bspc rule -a Processing border=off

if [ "$(hostname)" = pc ]; then
  bspc monitor DP-0 -d 1 2 3 4 5
  bspc monitor DP-4 -d 6 7 8 9 0
else # laptop
  bspc monitor -d 1 2 3 4 5 6 7 8 9
  gebaard -b
fi
