#!/bin/sh

"$HOME"/.config/polybar/launch.sh
hsetroot -solid "#6f9d76"
picom -b
setxkbmap -option "caps:swapescape"

bspc config border_width        0
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config single_monocle       true

bspc config focused_border_color  "#282828"
bspc config normal_border_color   "#282828"
bspc config urgent_border_color   "#282828"

bspc config pointer_modifier super
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none
bspc config focus_follows_pointer true

bspc config top_padding 30

bspc rule -a Blueman-manager state=floating
bspc rule -a Zoom state=floating
bspc rule -a Processing border=off

if [ "$(hostname)" = pc ]; then
  bspc monitor HDMI-1 -d 1 2 3 4 5
  bspc monitor DP-1 -d 6 7 8 9 0
else # laptop
  bspc monitor -d 1 2 3 4 5 6 7 8 9
  gebaard -b
fi
