#!/usr/bin/env bash

count=0
disconnected=" 睊 "
connected=" 直 "
ID="$(ip link | awk '/state UP/ {print $2}')"

while true; do
  if nc -zw1 conorknowles.com 443; then
    echo "$connected" ; sleep 25
  else
    echo "$disconnected" ; sleep 0.5
  fi
done
