#!/bin/bash

## Author : Aditya Shakya (adi1090x)
## Mail : adi1090x@gmail.com
## Github : @adi1090x
## Reddit : @adi1090x

rofi_command="rofi -location 3 -yoffset 32"

## Get info
IFACE="$(nmcli | grep -i interface | awk '/interface/ {print $2}')"
#SSID="$(iwgetid -r)"
#LIP="$(nmcli | grep -i server | awk '/server/ {print $2}')"
#PIP="$(dig +short myip.opendns.com @resolver1.opendns.com )"
STATUS="$(nmcli radio wifi)"

active=""
urgent=""

if (ping -c 1 archlinux.org || ping -c 1 google.com || ping -c 1 bitbucket.org || ping -c 1 github.com || ping -c 1 sourceforge.net) &>/dev/null; then
	if [[ $STATUS == *"enable"* ]]; then
        if [[ $IFACE == e* ]]; then
            connected="  Connected To Internet"
        else
            connected="  Connected To Internet"
        fi
	active="-a 0"
	SSID="$(iw dev | grep ssid | awk '{print $2}')"
	PIP="$(wget http://checkip.dyndns.org/ -O - -o /dev/null | cut -d: -f 2 | cut -d\< -f 1)"
	fi
else
    urgent="-u 0"
    SSID="Disconnected"
    PIP="NA"
    connected="\tOffline"
fi

## Icons
bmon="  Open Bandwidth Monitor"
launch_cli="  Open Network Manager"
launch="  Open Connection Editor"

options="$connected\n$bmon\n$launch_cli\n$launch"

## Main
chosen="$(echo -e "$options" | $rofi_command -p "$SSID @$PIP " -dmenu $active $urgent -selected-row 1)"
case $chosen in
  $connected)
    if [[ $STATUS == *"enable"* ]]; then
      nmcli radio wifi off
    else
      nmcli radio wifi on
    fi
    ;;
  $bmon)
    bspc rule -a \* -o state=floating && $TERMINAL -e bmon
    ;;
  $launch_cli)
    bspc rule -a \* -o state=floating && $TERMINAL -e nmtui
    ;;
  $launch)
    bspc rule -a \* -o state=floating && nm-connection-editor
    ;;
esac
